# Configuration:
# 
# disabled
#   false if tracking tag should be shown
# use_async
#   Set to true if you want to use asynchronous tracking
# url
#   The url of your piwik instance (e.g. localhost/piwik/
# id_site
#   The id of your website inside Piwik
#

development:
  piwik:
    id_site: 20
    url: stats.uke.gov.pl
    disabled: true
    use_async: false
    hostname: localhost

test:
  piwik:
    id_site: 20
    url: localhost
    disabled: true
    use_async: false
    hostname: localhost

production:
  piwik:
    id_site: 20
    url: stats.uke.gov.pl
    use_async: true
    disabled: false
